group=io.github.darkokoa
version=0.2.0

# Publication properties.
pomDescription=Kotlin Multiplatform (Kotlin MPP aka KMP) implementation of pangu.js
pomUrl=https://github.com/darkokoa/pangu.kt
pomLicenseName=MIT
pomLicenseUrl=https://opensource.org/licenses/MIT
pomScmUrl=https://github.com/darkokoa/pangu.kt
pomScmConnection=scm:git:git://github.com/darkokoa/pangu.kt.git
pomScmDeveloperConnection=scm:git:ssh://git@github.com:darkokoa/pangu.kt.git
pomDeveloperId=darkokoa
pomDeveloperName=darkokoa
pomDeveloperUrl=https://github.com/darkokoa

# Build properties.
kotlin.code.style=official
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.native.ignoreDisabledTargets=true
